### ISSUE TITLE
Поломанные стёкла в доме.

### ISSUE THREAD

**Issue by HotRikardo228** [mcrpg/public#35]
В посёлке Николаево стоит вот такой вот дом, стёкла поломаны.
![Screenshot_20200104-162059_Minecraft](https://user-images.githubusercontent.com/59420530/71766246-e0747e80-2f0e-11ea-9bf1-bc28f8e0d859.jpg)
![Screenshot_20200104-162055_Minecraft](https://user-images.githubusercontent.com/59420530/71766247-e0747e80-2f0e-11ea-80bb-f9cfaabfa616.jpg)

**Comment by mcrpg** [comment]
Проверено. Это часть дизайна, все в порядке.
