### ISSUE TITLE
Разработать плагин с командой /radio

### ISSUE THREAD

**Issue by HotRikardo228** [mcrpg/public#65]
Требуется разработать плагин с командой /radio (на Хотбаре такая команда имеется, но на самом деле таковой команды нет, требуется её добавление).
![jX4m1pKUBdM](https://user-images.githubusercontent.com/59420530/71813111-e2af1800-3089-11ea-8b1f-a70e527ff4cf.jpg)

**Comment by mcrpg** [comment]
дубликат #40
