### ISSUE TITLE
Отредактировать WIKI состава администрации

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/public#7]
Перенести все необходимые данные о составе администрации высшему составу каждому согласно **своему отделу**.

https://github.com/mcrpg/work/wiki

**Comment by mcrpg** [comment]
При внесении каждого человека в состав, должна быть указана ссылка пользователя git и ссылка на вк, например:

Иван Иванов:
github.com/user
vk.com/id0
Нарушения: 
- конфликт от 01.01.2020
Достижения: нет
Статус: в отпуске с 01.01.2020 (20 дней)

**Comment by FirzMob** [comment]
В работе

**Comment by StormLVV** [comment]
Ожидание регистрации участников в системе github.

**Comment by FirzMob** [comment]
Задание выполнено!

**Comment by ProCompTEAM** [comment]
@Aptemius2 пропущен срок сдачи

**Comment by HotRikardo228** [comment]
Задание выполнено, с появлением новых участников  WIKI будет редактироваться.
