### ISSUE TITLE
Оформление репозитория и команды MCRPG

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/public#8]
Разработать несколько вариантов оформления для команды MCRPG и ее сервисов

3 варианта изображений типа квадрат
900x900px

2 варианта изображений типа обложка
ширина сторон 1590x400px

Стиль и содержимое должно характеризовать направленность команды и ее настрой. Подробности у руководителей отдела.

**Comment by ArtemGrach** [comment]
Хорошо работа будет сделана по высшему классу

**Comment by ArtemGrach** [comment]
_Work done and successfully commissioned_

**Comment by mcrpg** [comment]
ждем архивчик

**Comment by ArtemGrach** [comment]
_Archive_ 
https://drive.google.com/folderview?id=1PR4vS1EOp3VGVTULgVwZJHbNAY56fW0f
